Issue#104 arq imp qld logica
UnBArqDsw2021-2/2021.2_G6_Jobz_docs pull request #114
Opened 2022-03-28 15:46 UTC by Balbinoo

closes #[104]

## Qual(is) o(s) documento(s) modificado(s)?
Foi realizada a abertura do documento de arquitetura,

## O que foi feito?
Foram criados os tópicos de qualidade, visão lógica e visão de implementação

## Imagens (se aplicável)
![image](https://user-images.githubusercontent.com/54644626/160436557-5c8b5d4c-7e52-455c-b1d5-335bbe888bb0.png)

2022-03-28 22:15 UTC, ilus1 commented
![image](https://user-images.githubusercontent.com/71859307/160495755-ef873625-af6b-4e29-93d0-39752d4479c8.png)
Algumas dessas, principalmente, django, react, poderiam ser links

![image](https://user-images.githubusercontent.com/71859307/160495820-750122ec-4b38-473b-ac27-2f441f8b8fde.png)
Podia ter uma descrição sobre o diagrama e o por que dele(todas os exemplos no caso).

![image](https://user-images.githubusercontent.com/71859307/160495936-d90218f4-de1a-4ab7-924a-b0865dc1afb7.png)
link pra iso talvez?

![image](https://user-images.githubusercontent.com/71859307/160495996-d89e3730-8f9e-4923-af40-c28a43f1b8c5.png)
um negrito nos pontos aqui ia ficar legal

Tabela ficou top 👍

2022-03-30 12:08 UTC, ilus1 commented on docs/_sidebar.md
> +  - [Arquitetura de Software](./pages/arquitetura/arquitetura.md)
Não que fosse um requisito, mas se vc criou o link pra arquitetura poderia ter colocado o link pros outros tbm

2022-03-30 12:09 UTC, ilus1 commented on docs/pages/arquitetura/arquitetura.md
> +A visão lógica tem o objetivo de representar a visão conceitual do projeto por meio de camadas, descrevendo melhor os elementos comportamentais e funcionalidades da arquitetura. Tendo isso em vista,
Poderia ter links para o "React.js" e pro "Frontend  da acplicação"
Descrição tbm ta bem simples, vcs pegaram da referencia?

2022-03-30 12:10 UTC, ilus1 commented on docs/pages/arquitetura/arquitetura.md
> +### 2.1 Diagrama de Classes
Ta faltando comentar um pouco sobre o diagrama.

2022-03-30 12:10 UTC, ilus1 commented on docs/pages/arquitetura/arquitetura.md
> +#### 2.2.1 Backend
Ta faltando comentar um pouco sobre.

2022-03-30 12:10 UTC, ilus1 commented on docs/pages/arquitetura/arquitetura.md
> +
Ta faltando comentar um pouco sobre.

2022-03-30 12:10 UTC, ilus1 commented on docs/pages/arquitetura/arquitetura.md
> +
Ta faltando comentar um pouco sobre.

2022-03-30 12:12 UTC, ilus1 commented on docs/pages/arquitetura/arquitetura.md
> +
Essa primeira frase ta bem parecida com a frase inicial da primeira descrição, acho que vale a pena pelo menos mudar ela

2022-03-30 12:13 UTC, ilus1 commented on docs/pages/arquitetura/arquitetura.md
> +A ISO/IEC é um padrão internacional de um modelo para medir de maneira mais sistemática e exata a qualidade de um software. Com isso
Acho que um link para a ISO aqui ficaria bom

2022-03-30 12:15 UTC, ilus1 commented on docs/pages/arquitetura/arquitetura.md
> +- Functionality: é considerado um fator crucial na qualidade do software, sendo as funções aquelas que resolverão os requisitos. É subdividida: suitability, accuracy, security, functionality complian
só faltaou um negrito aqui em

2022-03-30 12:15 UTC, ilus1 commented on docs/pages/arquitetura/arquitetura.md
> +|:--------------------:|:-----:|
👍

2022-03-30 12:15 UTC, ilus1 requested changes
Acho que tem algumas coisas que podem melhorar antes de jogar na master

2022-03-30 13:17 UTC, AntonioAldisio commented
Pessoal, lendo o documento seria interessante colocar a introdução explicando o documento. Também é bom colocar links dentro do documento. Por fim, explicar melhor os exemplos abortados.

2022-03-31 02:27 UTC, Balbinoo commented on docs/_sidebar.md
> +  - [Arquitetura de Software](./pages/arquitetura/arquitetura.md)
Isso precisava ter sido feito para usarmos como base na master

2022-03-31 02:49 UTC, Balbinoo commented on docs/pages/arquitetura/arquitetura.md
> +A visão lógica tem o objetivo de representar a visão conceitual do projeto por meio de camadas, descrevendo melhor os elementos comportamentais e funcionalidades da arquitetura. Tendo isso em vista,
resolvido

2022-03-31 02:50 UTC, Balbinoo commented on docs/pages/arquitetura/arquitetura.md
> +### 2.1 Diagrama de Classes
comentado

2022-03-31 02:50 UTC, Balbinoo commented on docs/pages/arquitetura/arquitetura.md
> +#### 2.2.1 Backend
comentado

2022-03-31 02:51 UTC, Balbinoo commented on docs/pages/arquitetura/arquitetura.md
> +
comentado

2022-03-31 02:51 UTC, Balbinoo commented on docs/pages/arquitetura/arquitetura.md
> +
comentado

2022-03-31 02:51 UTC, Balbinoo commented on docs/pages/arquitetura/arquitetura.md
> +
Resolvido

2022-03-31 02:51 UTC, Balbinoo commented on docs/pages/arquitetura/arquitetura.md
> +A ISO/IEC é um padrão internacional de um modelo para medir de maneira mais sistemática e exata a qualidade de um software. Com isso
Feito

2022-03-31 02:52 UTC, Balbinoo commented on docs/pages/arquitetura/arquitetura.md
> +- Functionality: é considerado um fator crucial na qualidade do software, sendo as funções aquelas que resolverão os requisitos. É subdividida: suitability, accuracy, security, functionality complian
Ficou bom com o negrito sim

2022-03-31 02:53 UTC, Balbinoo commented on docs/pages/arquitetura/arquitetura.md
> +|:--------------------:|:-----:|
show

2022-03-31 12:13 UTC, merged